# Generated by Django 2.2.2 on 2019-07-11 03:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('address_line_1', models.CharField(blank=True, max_length=1024, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=12, verbose_name='ZIP / Postal code')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='date ordered')),
                ('product_id', models.IntegerField()),
                ('volume', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('flavour', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbe.Customer')),
            ],
        ),
    ]
