# Generated by Django 2.2.2 on 2019-06-24 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Length has to be 10', regex='^\\d{10}$')])),
                ('address_line_1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(max_length=1024, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=12, verbose_name='ZIP / Postal code')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('volume', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('flavour', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='date ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbe.Customer')),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kbe.ProductOrder')),
            ],
        ),
    ]
