# Generated by Django 2.2.2 on 2019-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=6),
        ),
    ]
