# Generated by Django 2.2.2 on 2019-07-12 02:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kbe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavour',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='volume',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
