# Generated by Django 2.2.2 on 2020-08-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbe', '0003_auto_20190712_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
