# Generated by Django 2.2.2 on 2020-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbe', '0004_auto_20200808_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
