# Generated by Django 2.2.2 on 2020-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbe', '0005_auto_20200808_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
